### ISSUE TITLE
Please support Swift Package Management

### ISSUE THREAD

**Issue by daimajia** [AlexRoar/SwiftYFinance#2]
Hi Alex, thanks for your working on this project. 

Do you have any plan to support [Swift Package Management](https://swift.org/package-manager/)?

**Comment by alexdremov** [comment]
Hello
Nice to see that this project is in use. I'll think about adding the support. Considering that this is not really hard, it should be fast 

You always can create a pull request!

**Comment by alexdremov** [comment]
@daimajia, I added Swift Package support. It's currently in the main branch. 
I'll create a release as soon as CocoaPods recover from downtime as I need to run tests.

**Comment by alexdremov** [comment]
Waiting...
<img src="https://i.ibb.co/h86B56J/Screenshot-2021-07-27-at-12-51-43.png" alt="Screenshot-2021-07-27-at-12-51-43" border="0">

**Comment by daimajia** [comment]
And do you know if Yahoo Finance support websocket to get  price update information?

**Comment by daimajia** [comment]
> @daimajia, I added Swift Package support. It's currently in the main branch.
> I'll create a release as soon as CocoaPods recover from downtime as I need to run tests.

Thanks for your working on this!

**Comment by alexdremov** [comment]
> And do you know if Yahoo Finance support websocket to get price update information?

I'll check it

**Comment by alexdremov** [comment]
> Thanks for your working on this!

New version published
