### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by rawmean** [AlexRoar/SwiftYFinance#7]
Looks like Yahoo is requiring cookies/crumb to be set and this does not work anymore. Does it still work for you?

**Comment by nickofthyme** [comment]
Works for me, but it will always fail if you don't enable network connections in your app sandbox. See [developer docs](https://developer.apple.com/documentation/xcode/configuring-the-macos-app-sandbox#Enable-access-to-restricted-resources).

**Comment by alexdremov** [comment]
Honestly, I have no idea if this works ;)

It's an old project that relies on undocumented Yahoo api. According to the previous comment, the lib still works, which is great
